runtime: python37

instance_class: F4

handlers:
- url: /tff/static
  static_dir: static

- url: /.*
  script: auto
  secure: always

env_variables:
  REDIS_HOST: redis-11092.c124.us-central1-1.gce.cloud.redislabs.com
  REDIS_PORT: 11092
  REDIS_PASSWORD: ZabRAKcOiGeu8jE3CJmP6kLsd7sEBEhG
  DW_PROJECT_ID: mnhs-dw-prod
  GA_TRACKING_ID: UA-150674641-1